namespace MapManager
{
    internal static class Loc
    {
        internal static readonly Dictionary<string, Dictionary<string, string>> s_Translations = new()
        {
            ["MAPMANAGER_SECTION_MAIN"] = new()
            {
                ["English"]              = "Main",
                ["German"]               = "Allgemein",
                ["Russian"]              = "Основное",
                ["French (France)"]      = "Principal",
                ["Japanese"]             = "基本設定",
                ["Korean"]               = "기본 설정",
                ["Simplified Chinese"]   = "基本设置",
                ["Swedish"]              = "Allmänt",
                ["Traditional Chinese"]  = "基本設定",
                ["Turkish"]              = "Ana",
                ["Norwegian"]            = "Generelt",
                ["Spanish (Spain)"]      = "Principal",
                ["Portuguese (Portugal)"]= "Principal",
                ["Portuguese (Brazil)"]  = "Principal",
                ["Dutch"]                = "Algemeen",
                ["Finnish"]              = "Yleiset",
                ["Italian"]              = "Principale",
                ["Polish"]               = "Ogólne",
                ["Ukrainian"]            = "Основне",
            },
            ["MAPMANAGER_ENABLE_ARROW"] = new()
            {
                ["English"]              = "Enable Map Arrow",
                ["German"]               = "Kartenpfeil anzeigen",
                ["Russian"]              = "Показывать стрелку на карте",
                ["French (France)"]      = "Afficher la flèche sur la carte",
                ["Japanese"]             = "マップ矢印を有効にする",
                ["Korean"]               = "지도 화살표 활성화",
                ["Simplified Chinese"]   = "启用地图箭头",
                ["Swedish"]              = "Visa kartpil",
                ["Traditional Chinese"]  = "啟用地圖箭頭",
                ["Turkish"]              = "Harita okunu etkinleştir",
                ["Norwegian"]            = "Vis kartpil",
                ["Spanish (Spain)"]      = "Mostrar flecha en el mapa",
                ["Portuguese (Portugal)"]= "Mostrar seta no mapa",
                ["Portuguese (Brazil)"]  = "Mostrar seta no mapa",
                ["Dutch"]                = "Kaartpijl weergeven",
                ["Finnish"]              = "Näytä nuoli kartalla",
                ["Italian"]              = "Mostra freccia sulla mappa",
                ["Polish"]               = "Pokaż strzałkę na mapie",
                ["Ukrainian"]            = "Показати стрілку на карті",
            },
            ["MAPMANAGER_ENABLE_ARROW_DESC"] = new()
            {
                ["English"]              = "If enabled, will show where the player is on the map with an arrow",
                ["German"]               = "Zeigt die Position des Spielers auf der Karte mit einem Pfeil an",
                ["Russian"]              = "Если включено, показывает положение игрока на карте в виде стрелки",
                ["French (France)"]      = "Si activé, affiche la position du joueur sur la carte avec une flèche",
                ["Japanese"]             = "有効にすると、矢印でプレイヤーの位置をマップに表示します",
                ["Korean"]               = "활성화하면 화살표로 지도에 플레이어 위치를 표시합니다",
                ["Simplified Chinese"]   = "启用后，将用箭头在地图上显示玩家位置",
                ["Swedish"]              = "Om aktiverat visas spelarens position på kartan med en pil",
                ["Traditional Chinese"]  = "啟用後，將用箭頭在地圖上顯示玩家位置",
                ["Turkish"]              = "Etkinleştirilirse, oyuncunun harita üzerindeki konumunu bir okla gösterir",
                ["Norwegian"]            = "Hvis aktivert, vises spillerens posisjon på kartet med en pil",
                ["Spanish (Spain)"]      = "Si está activado, muestra la posición del jugador en el mapa con una flecha",
                ["Portuguese (Portugal)"]= "Se ativado, mostra a posição do jogador no mapa com uma seta",
                ["Portuguese (Brazil)"]  = "Se ativado, mostra a posição do jogador no mapa com uma seta",
                ["Dutch"]                = "Toont de positie van de speler op de kaart met een pijl",
                ["Finnish"]              = "Jos käytössä, näyttää pelaajan sijainnin kartalla nuolella",
                ["Italian"]              = "Se attivato, mostra la posizione del giocatore sulla mappa con una freccia",
                ["Polish"]               = "Jeśli włączone, pokazuje pozycję gracza na mapie za pomocą strzałki",
                ["Ukrainian"]            = "Якщо увімкнено, показує розташування гравця на карті стрілкою",
            },
            ["MAPMANAGER_CENTER_PLAYER"] = new()
            {
                ["English"]              = "Center on the Player",
                ["German"]               = "Auf Spieler zentrieren",
                ["Russian"]              = "Центрировать на игроке",
                ["French (France)"]      = "Centrer sur le joueur",
                ["Japanese"]             = "プレイヤーを中央に表示",
                ["Korean"]               = "플레이어 중심으로",
                ["Simplified Chinese"]   = "以玩家为中心",
                ["Swedish"]              = "Centrera på spelare",
                ["Traditional Chinese"]  = "以玩家為中心",
                ["Turkish"]              = "Oyuncuya ortala",
                ["Norwegian"]            = "Sentrer på spiller",
                ["Spanish (Spain)"]      = "Centrar en el jugador",
                ["Portuguese (Portugal)"]= "Centralizar no jogador",
                ["Portuguese (Brazil)"]  = "Centralizar no jogador",
                ["Dutch"]                = "Centreren op speler",
                ["Finnish"]              = "Keskitä pelaajaan",
                ["Italian"]              = "Centra sul giocatore",
                ["Polish"]               = "Wyśrodkuj na graczu",
                ["Ukrainian"]            = "Центрувати на гравці",
            },
            ["MAPMANAGER_CENTER_PLAYER_DESC"] = new()
            {
                ["English"]              = "If enabled, will center the map view on the player",
                ["German"]               = "Zentriert die Karte auf die Position des Spielers",
                ["Russian"]              = "Если включено, карта будет центрироваться на положении игрока",
                ["French (France)"]      = "Si activé, centre la carte sur la position du joueur",
                ["Japanese"]             = "有効にすると、マップをプレイヤーの位置に中央揃えします",
                ["Korean"]               = "활성화하면 지도를 플레이어 위치에 맞게 중앙에 배치합니다",
                ["Simplified Chinese"]   = "启用后，地图视图将以玩家位置为中心",
                ["Swedish"]              = "Om aktiverat centreras kartan på spelarens position",
                ["Traditional Chinese"]  = "啟用後，地圖視圖將以玩家位置為中心",
                ["Turkish"]              = "Etkinleştirilirse, haritayı oyuncunun konumuna ortalar",
                ["Norwegian"]            = "Hvis aktivert, sentreres kartet på spillerens posisjon",
                ["Spanish (Spain)"]      = "Si está activado, centra el mapa en la posición del jugador",
                ["Portuguese (Portugal)"]= "Se ativado, centraliza o mapa na posição do jogador",
                ["Portuguese (Brazil)"]  = "Se ativado, centraliza o mapa na posição do jogador",
                ["Dutch"]                = "Centreert de kaart op de positie van de speler",
                ["Finnish"]              = "Jos käytössä, kartta keskittyy pelaajan sijaintiin",
                ["Italian"]              = "Se attivato, centra la mappa sulla posizione del giocatore",
                ["Polish"]               = "Jeśli włączone, centruje mapę na pozycji gracza",
                ["Ukrainian"]            = "Якщо увімкнено, карта центрується на положенні гравця",
            },
            ["MAPMANAGER_REVEAL_MAP"] = new()
            {
                ["English"]              = "BETA: Reveal The Map",
                ["German"]               = "BETA: Karte aufdecken",
                ["Russian"]              = "БЕТА: Открыть карту",
                ["French (France)"]      = "BÊTA : Révéler la carte",
                ["Japanese"]             = "BETA: マップを全開示",
                ["Korean"]               = "베타: 지도 전체 공개",
                ["Simplified Chinese"]   = "BETA: 揭示地图",
                ["Swedish"]              = "BETA: Avslöja kartan",
                ["Traditional Chinese"]  = "BETA: 揭示地圖",
                ["Turkish"]              = "BETA: Haritayı Aç",
                ["Norwegian"]            = "BETA: Avslør kartet",
                ["Spanish (Spain)"]      = "BETA: Revelar el mapa",
                ["Portuguese (Portugal)"]= "BETA: Revelar o mapa",
                ["Portuguese (Brazil)"]  = "BETA: Revelar o mapa",
                ["Dutch"]                = "BETA: Kaart onthullen",
                ["Finnish"]              = "BEETA: Paljasta kartta",
                ["Italian"]              = "BETA: Rivela la mappa",
                ["Polish"]               = "BETA: Odkryj mapę",
                ["Ukrainian"]            = "БЕТА: Відкрити карту",
            },
            ["MAPMANAGER_REVEAL_MAP_DESC"] = new()
            {
                ["English"]              = "Set this key to reveal the entire current region on the map",
                ["German"]               = "Taste zum Aufdecken der gesamten Region auf der Karte",
                ["Russian"]              = "Клавиша для открытия всего текущего региона на карте",
                ["French (France)"]      = "Touche pour révéler l'intégralité de la région sur la carte",
                ["Japanese"]             = "現在の地域全体をマップに表示するキー",
                ["Korean"]               = "현재 지역 전체를 지도에 표시하는 키",
                ["Simplified Chinese"]   = "用于在地图上揭示整个当前区域的按键",
                ["Swedish"]              = "Tangent för att avslöja hela regionen på kartan",
                ["Traditional Chinese"]  = "用於在地圖上揭示整個當前區域的按鍵",
                ["Turkish"]              = "Haritada tüm bölgeyi açmak için kullanılacak tuş",
                ["Norwegian"]            = "Tast for å avsløre hele regionen på kartet",
                ["Spanish (Spain)"]      = "Tecla para revelar toda la región en el mapa",
                ["Portuguese (Portugal)"]= "Tecla para revelar toda a região no mapa",
                ["Portuguese (Brazil)"]  = "Tecla para revelar toda a região no mapa",
                ["Dutch"]                = "Toets om de gehele regio op de kaart te onthullen",
                ["Finnish"]              = "Näppäin koko alueen paljastamiseksi kartalla",
                ["Italian"]              = "Tasto per rivelare l'intera regione sulla mappa",
                ["Polish"]               = "Klawisz do odkrycia całego regionu na mapie",
                ["Ukrainian"]            = "Клавіша для відкриття всього поточного регіону на карті",
            },
            ["MAPMANAGER_SECTION_SURVEY"] = new()
            {
                ["English"]              = "Map Surveying",
                ["German"]               = "Kartierung",
                ["Russian"]              = "Картографирование",
                ["French (France)"]      = "Cartographie",
                ["Japanese"]             = "地図測量",
                ["Korean"]               = "지도 측량",
                ["Simplified Chinese"]   = "地图测量",
                ["Swedish"]              = "Kartläggning",
                ["Traditional Chinese"]  = "地圖測量",
                ["Turkish"]              = "Harita Araştırması",
                ["Norwegian"]            = "Kartlegging",
                ["Spanish (Spain)"]      = "Cartografía",
                ["Portuguese (Portugal)"]= "Cartografia",
                ["Portuguese (Brazil)"]  = "Cartografia",
                ["Dutch"]                = "Kaartverkenning",
                ["Finnish"]              = "Kartoitus",
                ["Italian"]              = "Cartografia",
                ["Polish"]               = "Kartografia",
                ["Ukrainian"]            = "Картографування",
            },
            ["MAPMANAGER_RANGE_MULT"] = new()
            {
                ["English"]              = "Range Multiplier",
                ["German"]               = "Reichweitenmultiplikator",
                ["Russian"]              = "Множитель дальности",
                ["French (France)"]      = "Multiplicateur de portée",
                ["Japanese"]             = "範囲倍率",
                ["Korean"]               = "범위 배율",
                ["Simplified Chinese"]   = "范围倍数",
                ["Swedish"]              = "Räckviddsmultiplikator",
                ["Traditional Chinese"]  = "範圍倍數",
                ["Turkish"]              = "Menzil çarpanı",
                ["Norwegian"]            = "Rekkeviddemultiplikator",
                ["Spanish (Spain)"]      = "Multiplicador de alcance",
                ["Portuguese (Portugal)"]= "Multiplicador de alcance",
                ["Portuguese (Brazil)"]  = "Multiplicador de alcance",
                ["Dutch"]                = "Bereiksmultiplikator",
                ["Finnish"]              = "Kantaman kerroin",
                ["Italian"]              = "Moltiplicatore di portata",
                ["Polish"]               = "Mnożnik zasięgu",
                ["Ukrainian"]            = "Множник дальності",
            },
            ["MAPMANAGER_SURVEY_TIME"] = new()
            {
                ["English"]              = "Survey Time Multiplier",
                ["German"]               = "Kartierungs-Zeitmultiplikator",
                ["Russian"]              = "Множитель времени картографирования",
                ["French (France)"]      = "Multiplicateur de temps de cartographie",
                ["Japanese"]             = "測量時間倍率",
                ["Korean"]               = "측량 시간 배율",
                ["Simplified Chinese"]   = "测量时间倍数",
                ["Swedish"]              = "Tidsmultiplikator för kartläggning",
                ["Traditional Chinese"]  = "測量時間倍數",
                ["Turkish"]              = "Araştırma süresi çarpanı",
                ["Norwegian"]            = "Tidsmultiplikator for kartlegging",
                ["Spanish (Spain)"]      = "Multiplicador de tiempo de cartografía",
                ["Portuguese (Portugal)"]= "Multiplicador de tempo de cartografia",
                ["Portuguese (Brazil)"]  = "Multiplicador de tempo de cartografia",
                ["Dutch"]                = "Tijdsmultiplikator verkenning",
                ["Finnish"]              = "Kartoitusajan kerroin",
                ["Italian"]              = "Moltiplicatore del tempo di rilevamento",
                ["Polish"]               = "Mnożnik czasu kartografii",
                ["Ukrainian"]            = "Множник часу картографування",
            },
            ["MAPMANAGER_SURVEY_TIME_DESC"] = new()
            {
                ["English"]              = "The amount of time it takes to survey",
                ["German"]               = "Die Zeit, die für die Kartierung benötigt wird",
                ["Russian"]              = "Количество времени, необходимое для картографирования",
                ["French (France)"]      = "La durée nécessaire pour cartographier",
                ["Japanese"]             = "測量に必要な時間",
                ["Korean"]               = "측량에 필요한 시간",
                ["Simplified Chinese"]   = "进行测量所需的时间",
                ["Swedish"]              = "Tid som behövs för kartläggning",
                ["Traditional Chinese"]  = "進行測量所需的時間",
                ["Turkish"]              = "Araştırma için gereken süre",
                ["Norwegian"]            = "Tid som trengs for kartlegging",
                ["Spanish (Spain)"]      = "El tiempo necesario para cartografiar",
                ["Portuguese (Portugal)"]= "O tempo necessário para cartografiar",
                ["Portuguese (Brazil)"]  = "O tempo necessário para cartografiar",
                ["Dutch"]                = "De tijd die nodig is voor verkenning",
                ["Finnish"]              = "Kartoitukseen tarvittava aika",
                ["Italian"]              = "Il tempo necessario per effettuare il rilevamento",
                ["Polish"]               = "Czas potrzebny do kartografii",
                ["Ukrainian"]            = "Час, необхідний для картографування",
            },
            ["MAPMANAGER_POLAROID"] = new()
            {
                ["English"]              = "Polaroids Always Discovered",
                ["German"]               = "Polaroids immer entdeckt",
                ["Russian"]              = "Поляроиды всегда обнаруживаются",
                ["French (France)"]      = "Polaroïds toujours découverts",
                ["Japanese"]             = "ポラロイドを常に発見済み",
                ["Korean"]               = "폴라로이드 항상 발견됨",
                ["Simplified Chinese"]   = "始终发现拍立得",
                ["Swedish"]              = "Polaroidbilder alltid upptäckta",
                ["Traditional Chinese"]  = "始終發現拍立得",
                ["Turkish"]              = "Polaroidler her zaman keşfedildi",
                ["Norwegian"]            = "Polaroidbilder alltid oppdaget",
                ["Spanish (Spain)"]      = "Polaroids siempre descubiertos",
                ["Portuguese (Portugal)"]= "Polaroids sempre descobertos",
                ["Portuguese (Brazil)"]  = "Polaroids sempre descobertos",
                ["Dutch"]                = "Polaroids altijd ontdekt",
                ["Finnish"]              = "Polaroidit aina löydetty",
                ["Italian"]              = "Polaroid sempre scoperti",
                ["Polish"]               = "Polaroidy zawsze odkryte",
                ["Ukrainian"]            = "Полароїди завжди виявляються",
            },
            ["MAPMANAGER_POLAROID_DESC"] = new()
            {
                ["English"]              = "Surveying vistas without a polaroid will add the relevant polaroid to your inventory",
                ["German"]               = "Das Erkunden von Aussichtspunkten ohne Polaroid fügt das entsprechende Polaroid dem Inventar hinzu",
                ["Russian"]              = "Обследование панорам без поляроида добавит соответствующий поляроид в инвентарь",
                ["French (France)"]      = "Explorer des panoramas sans polaroïd ajoute le polaroïd correspondant à l'inventaire",
                ["Japanese"]             = "ポラロイドなしで展望台を調査すると、対応するポラロイドがインベントリに追加されます",
                ["Korean"]               = "폴라로이드 없이 전망대를 탐사하면 해당 폴라로이드가 인벤토리에 추가됩니다",
                ["Simplified Chinese"]   = "没有拍立得也能探索景点，并将相应的拍立得添加到物品栏中",
                ["Swedish"]              = "Utforskning av vyer utan polaroid lägger till relevant polaroid i inventariet",
                ["Traditional Chinese"]  = "沒有拍立得也能探索景點，並將相應的拍立得添加到物品欄中",
                ["Turkish"]              = "Polaroid olmadan manzara araştırmak ilgili Polaroid'i envantere ekler",
                ["Norwegian"]            = "Utforskning av utsiktspunkter uten polaroid legger til relevant polaroid i inventaret",
                ["Spanish (Spain)"]      = "Explorar panoramas sin polaroid añade el polaroid correspondiente al inventario",
                ["Portuguese (Portugal)"]= "Explorar panoramas sem polaroid adiciona o polaroid correspondente ao inventário",
                ["Portuguese (Brazil)"]  = "Explorar panoramas sem polaroid adiciona o polaroid correspondente ao inventário",
                ["Dutch"]                = "Verkenning van uitzichtpunten zonder polaroid voegt de bijbehorende polaroid toe aan het inventaris",
                ["Finnish"]              = "Maisemien tutkiminen ilman polaroidia lisää asianmukaisen polaroidin inventaarioon",
                ["Italian"]              = "L'esplorazione di panorami senza polaroid aggiunge il polaroid corrispondente all'inventario",
                ["Polish"]               = "Badanie panoram bez polaroidu doda odpowiedni polaroid do ekwipunku",
                ["Ukrainian"]            = "Дослідження панорам без полароїду додасть відповідний полароїд до інвентаря",
            },
            ["MAPMANAGER_REVEAL_VISTA"] = new()
            {
                ["English"]              = "Reveal Vista Locations",
                ["German"]               = "Aussichtspunkte aufdecken",
                ["Russian"]              = "Открывать обзорные точки",
                ["French (France)"]      = "Révéler les emplacements panoramiques",
                ["Japanese"]             = "展望台の場所を表示",
                ["Korean"]               = "전망대 위치 표시",
                ["Simplified Chinese"]   = "揭示景点位置",
                ["Swedish"]              = "Avslöja vyplatser",
                ["Traditional Chinese"]  = "揭示景點位置",
                ["Turkish"]              = "Manzara konumlarını aç",
                ["Norwegian"]            = "Avslør utsiktssteder",
                ["Spanish (Spain)"]      = "Revelar ubicaciones de panoramas",
                ["Portuguese (Portugal)"]= "Revelar locais de panoramas",
                ["Portuguese (Brazil)"]  = "Revelar locais de panoramas",
                ["Dutch"]                = "Uitzichtlocaties onthullen",
                ["Finnish"]              = "Paljasta maisemapaikat",
                ["Italian"]              = "Rivela le posizioni panoramiche",
                ["Polish"]               = "Odkryj lokalizacje panoram",
                ["Ukrainian"]            = "Відкрити панорамні місця",
            },
            ["MAPMANAGER_REVEAL_VISTA_DESC"] = new()
            {
                ["English"]              = "Will force reveal any vista locations within range",
                ["German"]               = "Erzwingt die Aufdeckung aller Aussichtspunkte im Bereich",
                ["Russian"]              = "Принудительно открывает обзорные точки в радиусе действия",
                ["French (France)"]      = "Force la révélation des emplacements panoramiques dans la portée",
                ["Japanese"]             = "範囲内の展望台の場所を強制的に表示します",
                ["Korean"]               = "범위 내 전망대 위치를 강제로 표시합니다",
                ["Simplified Chinese"]   = "强制揭示范围内的所有景点位置",
                ["Swedish"]              = "Tvingar fram avslöjande av vyplatser inom räckhåll",
                ["Traditional Chinese"]  = "強制揭示範圍內的所有景點位置",
                ["Turkish"]              = "Menzil içindeki tüm manzara konumlarını zorla açar",
                ["Norwegian"]            = "Tvinger frem avsløring av utsiktssteder innen rekkevidde",
                ["Spanish (Spain)"]      = "Fuerza la revelación de ubicaciones panorámicas en el rango",
                ["Portuguese (Portugal)"]= "Força a revelação de locais panorâmicos no alcance",
                ["Portuguese (Brazil)"]  = "Força a revelação de locais panorâmicos no alcance",
                ["Dutch"]                = "Onthult alle uitzichtlocaties binnen bereik",
                ["Finnish"]              = "Pakottaa maisemapaikkojen paljastamisen kantaman sisällä",
                ["Italian"]              = "Forza la rivelazione delle posizioni panoramiche nel raggio d'azione",
                ["Polish"]               = "Wymusza odkrycie lokalizacji panoram w zasięgu",
                ["Ukrainian"]            = "Примусово відкриває панорамні місця в радіусі дії",
            },
            ["MAPMANAGER_UNLOCK_SURVEY"] = new()
            {
                ["English"]              = "Unlock Survey",
                ["German"]               = "Kartierung freischalten",
                ["Russian"]              = "Разблокировать картографирование",
                ["French (France)"]      = "Débloquer la cartographie",
                ["Japanese"]             = "測量をいつでも可能にする",
                ["Korean"]               = "측량 잠금 해제",
                ["Simplified Chinese"]   = "解锁测量功能",
                ["Swedish"]              = "Lås upp kartläggning",
                ["Traditional Chinese"]  = "解鎖測量功能",
                ["Turkish"]              = "Araştırmayı kilitle aç",
                ["Norwegian"]            = "Lås opp kartlegging",
                ["Spanish (Spain)"]      = "Desbloquear cartografía",
                ["Portuguese (Portugal)"]= "Desbloquear cartografia",
                ["Portuguese (Brazil)"]  = "Desbloquear cartografia",
                ["Dutch"]                = "Verkenning ontgrendelen",
                ["Finnish"]              = "Avaa kartoitus",
                ["Italian"]              = "Sblocca il rilevamento",
                ["Polish"]               = "Odblokuj kartografię",
                ["Ukrainian"]            = "Розблокувати картографування",
            },
            ["MAPMANAGER_UNLOCK_SURVEY_DESC"] = new()
            {
                ["English"]              = "Allow surveying at any time",
                ["German"]               = "Ermöglicht Kartierung zu jeder Zeit",
                ["Russian"]              = "Разрешает картографирование в любое время",
                ["French (France)"]      = "Permet la cartographie à tout moment",
                ["Japanese"]             = "いつでも測量できるようにします",
                ["Korean"]               = "언제든지 측량할 수 있도록 합니다",
                ["Simplified Chinese"]   = "允许随时进行测量",
                ["Swedish"]              = "Tillåter kartläggning när som helst",
                ["Traditional Chinese"]  = "允許隨時進行測量",
                ["Turkish"]              = "Her zaman araştırma yapılmasına izin verir",
                ["Norwegian"]            = "Tillater kartlegging til enhver tid",
                ["Spanish (Spain)"]      = "Permite cartografiar en cualquier momento",
                ["Portuguese (Portugal)"]= "Permite cartografiar a qualquer momento",
                ["Portuguese (Brazil)"]  = "Permite cartografiar a qualquer momento",
                ["Dutch"]                = "Staat verkenning op elk moment toe",
                ["Finnish"]              = "Sallii kartoituksen milloin tahansa",
                ["Italian"]              = "Consente il rilevamento in qualsiasi momento",
                ["Polish"]               = "Pozwala na kartografię w dowolnym czasie",
                ["Ukrainian"]            = "Дозволяє картографування будь-коли",
            },
            ["MAPMANAGER_ADD_CORPSE"] = new()
            {
                ["English"]              = "Add Dead Corpses to Map",
                ["German"]               = "Kadaver zur Karte hinzufügen",
                ["Russian"]              = "Добавлять трупы на карту",
                ["French (France)"]      = "Ajouter les cadavres à la carte",
                ["Japanese"]             = "死体をマップに追加",
                ["Korean"]               = "시체를 지도에 추가",
                ["Simplified Chinese"]   = "将尸体添加到地图",
                ["Swedish"]              = "Lägg till kadaver på kartan",
                ["Traditional Chinese"]  = "將屍體添加到地圖",
                ["Turkish"]              = "Cesetleri haritaya ekle",
                ["Norwegian"]            = "Legg til kadavere på kartet",
                ["Spanish (Spain)"]      = "Añadir cadáveres al mapa",
                ["Portuguese (Portugal)"]= "Adicionar cadáveres ao mapa",
                ["Portuguese (Brazil)"]  = "Adicionar cadáveres ao mapa",
                ["Dutch"]                = "Kadavers aan kaart toevoegen",
                ["Finnish"]              = "Lisää ruumiit kartalle",
                ["Italian"]              = "Aggiungi cadaveri alla mappa",
                ["Polish"]               = "Dodaj zwłoki do mapy",
                ["Ukrainian"]            = "Додати трупи на карту",
            },
            ["MAPMANAGER_ADD_CORPSE_DESC"] = new()
            {
                ["English"]              = "Automatically adds all dead animal corpses to the map",
                ["German"]               = "Fügt automatisch alle toten Tierkadaver zur Karte hinzu",
                ["Russian"]              = "Автоматически добавляет все трупы животных на карту",
                ["French (France)"]      = "Ajoute automatiquement tous les cadavres d'animaux à la carte",
                ["Japanese"]             = "すべての動物の死体を自動的にマップに追加します",
                ["Korean"]               = "모든 동물 시체를 자동으로 지도에 추가합니다",
                ["Simplified Chinese"]   = "自动将所有动物尸体添加到地图",
                ["Swedish"]              = "Lägger automatiskt till alla döda djurkadaver på kartan",
                ["Traditional Chinese"]  = "自動將所有動物屍體添加到地圖",
                ["Turkish"]              = "Tüm ölü hayvan cesetlerini otomatik olarak haritaya ekler",
                ["Norwegian"]            = "Legger automatisk til alle døde dyrekadavere på kartet",
                ["Spanish (Spain)"]      = "Añade automáticamente todos los cadáveres de animales al mapa",
                ["Portuguese (Portugal)"]= "Adiciona automaticamente todos os cadáveres de animais ao mapa",
                ["Portuguese (Brazil)"]  = "Adiciona automaticamente todos os cadáveres de animais ao mapa",
                ["Dutch"]                = "Voegt automatisch alle dode dierenkadavers aan de kaart toe",
                ["Finnish"]              = "Lisää automaattisesti kaikki eläinten ruumiit kartalle",
                ["Italian"]              = "Aggiunge automaticamente tutti i cadaveri di animali alla mappa",
                ["Polish"]               = "Automatycznie dodaje wszystkie trupy zwierząt do mapy",
                ["Ukrainian"]            = "Автоматично додає всі трупи тварин на карту",
            },
        };
    }
}
